// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: XrFaLLxdMpb
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For durable imperative Gradle logic, use build.extra.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

plugins {
    id("org.jetbrains.kotlin.jvm") version "2.3.10" apply false
    id("org.jetbrains.kotlin.js") version "2.3.10" apply false
    id("org.jetbrains.kotlin.multiplatform") version "2.3.10" apply false
    id("org.jetbrains.kotlin.plugin.serialization") version "2.3.10" apply false
    id("org.jetbrains.kotlin.plugin.compose") version "2.3.10" apply false
    id("com.android.application") version "8.12.0" apply false
    id("com.android.library") version "8.12.0" apply false
    id("com.android.kotlin.multiplatform.library") version "8.12.0" apply false
    id("org.jetbrains.compose") version "1.9.1" apply false
    id("com.gradleup.shadow") version "8.3.0" apply false
    id("org.jetbrains.dokka") version "2.0.0" apply false
    id("org.jetbrains.kotlinx.kover") version "0.9.3" apply false
    id("com.vanniktech.maven.publish") version "0.36.0" apply false
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
