// Generated by app-wabbit-dev setup. Do not edit by hand.

plugins {
    id("org.jetbrains.kotlin.jvm") apply false
    id("org.jetbrains.kotlin.js") apply false
    id("org.jetbrains.kotlin.multiplatform") apply false
    id("org.jetbrains.kotlin.plugin.serialization") apply false
    id("org.jetbrains.kotlin.plugin.compose") apply false
    id("com.android.application") version "8.12.0" apply false
    id("com.android.library") version "8.12.0" apply false
    id("com.android.kotlin.multiplatform.library") version "8.12.0" apply false
    id("org.jetbrains.compose") version "1.9.1" apply false
    id("com.gradleup.shadow") version "8.3.0" apply false
    id("org.jetbrains.dokka") version "2.0.0" apply false
    id("org.jetbrains.kotlinx.kover") version "0.9.3" apply false
    id("com.vanniktech.maven.publish") version "0.36.0" apply false
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
