// Generated by app-wabbit-dev setup. Do not edit by hand.

import org.jetbrains.dokka.gradle.DokkaExtension
import org.jetbrains.dokka.gradle.engine.plugins.DokkaHtmlPluginParameters
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

repositories {
    google()
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }

    maven("https://jitpack.io")
}

group   = "one.wabbit"

val kotlinVersion =
    providers.gradleProperty("kotlinVersion")
        .orElse(providers.gradleProperty("defaultKotlinVersion"))
        .orElse("2.3.10")
        .get()

version = "0.0.2"

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    id("org.jetbrains.intellij.platform")

    id("maven-publish")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "one.wabbit"
            artifactId = "kotlin-typeclasses-ij-plugin"
            version = project.version.toString()
            from(components["java"])
        }
    }
}

dependencies {
    testImplementation(kotlin("test"))
    intellijPlatform {
            intellijIdea("2025.3") {
                useInstaller = false
            }
            jetbrainsRuntime()
            bundledPlugins(
                listOf(
                    "com.intellij.gradle",
                    "org.jetbrains.kotlin"
                )
            )
            testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform)
        }
}

java {
    targetCompatibility = JavaVersion.toVersion(17)
    sourceCompatibility = JavaVersion.toVersion(17)
}

val configuredVersionString = version.toString()

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(17)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
            freeCompilerArgs.add("-Xcontext-parameters")

        }
    }

    jar {
        setProperty("zip64", true)

    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = provider { "253" }

            untilBuild = provider { null }

        }
    }
    publishing {
        token = providers.environmentVariable("JETBRAINS_MARKETPLACE_TOKEN")
        channels = listOf("default")
    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("kotlin-typeclasses-ij-plugin Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

plugins.withId("org.jetbrains.dokka") {
    afterEvaluate {
        extensions.findByType(DokkaExtension::class)?.apply {
            moduleName.set("kotlin-typeclasses-ij-plugin")
            dokkaPublications.named("html").configure {
                suppressInheritedMembers.set(true)
                failOnWarning.set(true)
            }
            dokkaSourceSets.named("main").configure {
                val dokkaModuleFile = file("docs/dokka-module.md")
                if (dokkaModuleFile.exists()) {
                    includes.from(dokkaModuleFile)
                }

                sourceLink {
                    localDirectory.set(file("src/main/kotlin"))
                    remoteUrl("https://github.com/wabbit-corp/kotlin-typeclasses/tree/master/ij-plugin/src/main/kotlin")
                    remoteLineSuffix.set("#L")
                }

            }
            pluginsConfiguration.named(DokkaHtmlPluginParameters.DOKKA_HTML_PARAMETERS_NAME).configure {
                (this as DokkaHtmlPluginParameters).footerMessage.set("(c) Wabbit Consulting Corporation")
            }
        }
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
