// Generated by app-wabbit-dev setup. Do not edit by hand.

import org.jetbrains.dokka.gradle.DokkaExtension
import org.jetbrains.dokka.gradle.engine.plugins.DokkaHtmlPluginParameters
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

repositories {
    google()
    mavenCentral()

    maven("https://jitpack.io")
}

group   = "one.wabbit"

val configuredBaseVersionString = providers.gradleProperty("projectVersion").orElse("0.0.1").get()

val kotlinVersion =
    providers.gradleProperty("kotlinVersion")
        .orElse(providers.gradleProperty("defaultKotlinVersion"))
        .orElse("2.3.10")
        .get()

fun compilerPluginPublicationVersion(baseVersion: String, kotlinVersion: String): String {
    val snapshotSuffix = "+dev-SNAPSHOT"
    return if (baseVersion.endsWith(snapshotSuffix)) {
        "${baseVersion.removeSuffix(snapshotSuffix)}-kotlin-$kotlinVersion$snapshotSuffix"
    } else {
        "$baseVersion-kotlin-$kotlinVersion"
    }
}

version = compilerPluginPublicationVersion(configuredBaseVersionString, kotlinVersion)

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    id("maven-publish")

    id("com.vanniktech.maven.publish")
}

mavenPublishing {
    coordinates("one.wabbit", "kotlin-typeclasses-plugin", project.version.toString())
    publishToMavenCentral()
    signAllPublications()
    pom {
        name.set("kotlin-typeclasses-plugin")
        description.set("kotlin-typeclasses-plugin")
        url.set("https://github.com/wabbit-corp/kotlin-typeclasses")
        licenses {
            license {
                name.set("GNU Affero General Public License v3.0 or later")
                url.set("https://spdx.org/licenses/AGPL-3.0-or-later.html")
            }
        }
        developers {
            developer {
                id.set("wabbit-corp")
                name.set("Wabbit Consulting Corporation")

                email.set("wabbit@wabbit.one")

            }
        }
        scm {
            url.set("https://github.com/wabbit-corp/kotlin-typeclasses")
            connection.set("scm:git:git://github.com/wabbit-corp/kotlin-typeclasses.git")
            developerConnection.set("scm:git:ssh://git@github.com/wabbit-corp/kotlin-typeclasses.git")
        }
    }
}

val localPublishRequested =
    gradle.startParameter.taskNames.any { taskName -> "MavenLocal" in taskName }

if (localPublishRequested) {
    tasks.withType<org.gradle.plugins.signing.Sign>().configureEach {
        enabled = false
    }
}

dependencies {
    implementation(project(":kotlin-typeclasses")) // 0.0.1

    testImplementation(kotlin("test"))

    compileOnly("org.jetbrains.kotlin:kotlin-compiler-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.9.0")
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.9.0")
    testImplementation("org.jetbrains.compose.desktop:desktop-jvm:1.9.1")
    testImplementation("org.jetbrains.kotlin:kotlin-serialization-compiler-plugin-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-compose-compiler-plugin-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-power-assert-compiler-plugin-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-parcelize-runtime:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-parcelize-compiler:$kotlinVersion")
    testImplementation("org.jetbrains.kotlinx:atomicfu-jvm:0.23.2")
    testImplementation("org.jetbrains.kotlin:kotlin-atomicfu-compiler-plugin-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-allopen-compiler-plugin-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-noarg-compiler-plugin-embeddable:$kotlinVersion")
}

val compilerCompatibilitySourceDirectory =
    layout.projectDirectory.dir(
        when {
            kotlinVersion.startsWith("2.3") -> "src/kotlin2_3/kotlin"

            kotlinVersion.startsWith("2.4") -> "src/kotlin2_4/kotlin"

            else -> error("Unsupported Kotlin version $kotlinVersion")
        },
    )

kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(compilerCompatibilitySourceDirectory)
    }
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()

val configuredBaseVersionForChecks = configuredBaseVersionString

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("printBaseVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionForChecks)
    doLast {
        println(inputs.properties["configuredBaseVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredBaseVersionForChecks)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredBaseVersionForChecks)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
            freeCompilerArgs.add("-Xcontext-parameters")

        }
    }

    jar {
        setProperty("zip64", true)

    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("kotlin-typeclasses-plugin Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

plugins.withId("org.jetbrains.dokka") {
    afterEvaluate {
        extensions.findByType(DokkaExtension::class)?.apply {
            moduleName.set("kotlin-typeclasses-plugin")
            dokkaPublications.named("html").configure {
                suppressInheritedMembers.set(true)
                failOnWarning.set(true)
            }
            dokkaSourceSets.named("main").configure {
                val dokkaModuleFile = file("docs/dokka-module.md")
                if (dokkaModuleFile.exists()) {
                    includes.from(dokkaModuleFile)
                }

                sourceLink {
                    localDirectory.set(file("src/main/kotlin"))
                    remoteUrl("https://github.com/wabbit-corp/kotlin-typeclasses/tree/master/compiler-plugin/src/main/kotlin")
                    remoteLineSuffix.set("#L")
                }

            }
            pluginsConfiguration.named(DokkaHtmlPluginParameters.DOKKA_HTML_PARAMETERS_NAME).configure {
                (this as DokkaHtmlPluginParameters).footerMessage.set("(c) Wabbit Consulting Corporation")
            }
        }
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
