// Generated by app-wabbit-dev setup. Do not edit by hand.

import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

fun compilerPluginPublicationVersion(baseVersion: String, kotlinVersion: String): String {
    val snapshotSuffix = "+dev-SNAPSHOT"
    return if (baseVersion.endsWith(snapshotSuffix)) {
        "${baseVersion.removeSuffix(snapshotSuffix)}-kotlin-$kotlinVersion$snapshotSuffix"
    } else {
        "$baseVersion-kotlin-$kotlinVersion"
    }
}

repositories {
    if (rootProject.file("settings.local.gradle.kts").isFile()) {
        mavenLocal {
            content {
                includeGroup("one.wabbit")
            }
        }
    }
    mavenCentral()

    maven("https://jitpack.io")
}

group   = "one.wabbit"
val configuredBaseVersionString = providers.gradleProperty("projectVersion").orElse("0.0.1").get()
val kotlinVersion =
    providers.gradleProperty("kotlinVersion")
        .orElse(providers.gradleProperty("defaultKotlinVersion"))
        .orElse("2.3.10")
        .get()
version = compilerPluginPublicationVersion(configuredBaseVersionString, kotlinVersion)
val firCompatibilitySourceDirectory =
    layout.projectDirectory.dir(
        if (kotlinVersion.startsWith("2.4")) {
            "src/kotlin2_4/kotlin"
        } else {
            "src/kotlin2_3/kotlin"
        },
    )

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    id("maven-publish")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "one.wabbit"
            artifactId = "kotlin-typeclasses-plugin"
            version = project.version.toString()
            from(components["java"])
        }
    }
}

dependencies {
    implementation(project(":kotlin-typeclasses")) // 0.0.1

    testImplementation(kotlin("test"))

    compileOnly("org.jetbrains.kotlin:kotlin-compiler-embeddable:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-compiler-embeddable:$kotlinVersion")
}

kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(firCompatibilitySourceDirectory)
    }
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("printBaseVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionString)
    doLast {
        println(inputs.properties["configuredBaseVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionString)
    doLast {
        val versionString = inputs.properties["configuredBaseVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionString)
    doLast {
        val versionString = inputs.properties["configuredBaseVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
            freeCompilerArgs.add("-Xcontext-parameters")

        }
    }

    jar {
        setProperty("zip64", true)

    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("kotlin-typeclasses-plugin Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

dokka {
    moduleName.set("kotlin-typeclasses-plugin")
    dokkaPublications.html {
        suppressInheritedMembers.set(true)
        failOnWarning.set(true)
    }
    dokkaSourceSets.main {
        val dokkaModuleFile = file("docs/dokka-module.md")
        if (dokkaModuleFile.exists()) {
            includes.from(dokkaModuleFile)
        }

        sourceLink {
            localDirectory.set(file("src/main/kotlin"))
            remoteUrl("https://github.com/wabbit-corp/kotlin-typeclasses/tree/master/compiler-plugin/src/main/kotlin")
            remoteLineSuffix.set("#L")
        }

    }
    pluginsConfiguration.html {
        // customStyleSheets.from("styles.css")
        // customAssets.from("logo.png")
        footerMessage.set("(c) Wabbit Consulting Corporation")
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
