// Generated by app-wabbit-dev setup. Do not edit by hand.

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

abstract class GenerateTypeclassGradlePluginVersion : DefaultTask() {
    @get:Input
    abstract val compilerPluginVersion: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package one.wabbit.typeclass.gradle

            internal const val TYPECLASS_GRADLE_PLUGIN_VERSION: String = "${compilerPluginVersion.get()}"
            """.trimIndent(),
        )
    }
}

repositories {
    if (rootProject.file("settings.local.gradle.kts").isFile()) {
        mavenLocal {
            content {
                includeGroup("one.wabbit")
            }
        }
    }
    mavenCentral()

    maven("https://jitpack.io")
}

group   = "one.wabbit"
val configuredBaseVersionString = providers.gradleProperty("projectVersion").orElse("0.0.1").get()
val kotlinVersion =
    providers.gradleProperty("kotlinVersion")
        .orElse(providers.gradleProperty("defaultKotlinVersion"))
        .orElse("2.3.10")
        .get()
version = configuredBaseVersionString

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    `java-gradle-plugin`

    id("maven-publish")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "one.wabbit"
            artifactId = "kotlin-typeclasses-gradle-plugin"
            version = project.version.toString()
            from(components["java"])
        }
    }
}

dependencies {
    compileOnly("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    testImplementation(gradleApi())
    testImplementation(gradleTestKit())

    testImplementation(kotlin("test"))
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()
val generatedVersionSourceDirectory = layout.buildDirectory.dir("generated/sources/typeclassVersion/main/kotlin")

val generateTypeclassGradlePluginVersion by tasks.registering(GenerateTypeclassGradlePluginVersion::class) {
    compilerPluginVersion.set(configuredBaseVersionString)
    outputFile.set(generatedVersionSourceDirectory.map { directory ->
        directory.file("one/wabbit/typeclass/gradle/TypeclassGradlePluginVersion.kt")
    })
}

kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(generatedVersionSourceDirectory)
    }
}

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("printBaseVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionString)
    doLast {
        println(inputs.properties["configuredBaseVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionString)
    doLast {
        val versionString = inputs.properties["configuredBaseVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionString)
    doLast {
        val versionString = inputs.properties["configuredBaseVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        dependsOn(generateTypeclassGradlePluginVersion)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
            freeCompilerArgs.add("-Xcontext-parameters")

        }
    }

    jar {
        setProperty("zip64", true)

    }
}

gradlePlugin {
    plugins {
        create("typeclass") {
            id = "one.wabbit.typeclass"
            implementationClass = "one.wabbit.typeclass.gradle.TypeclassGradlePlugin"
            displayName = "Typeclass Gradle plugin"
            description = "Gradle plugin for one.wabbit.typeclass."
        }
    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("kotlin-typeclasses-gradle-plugin Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

dokka {
    moduleName.set("kotlin-typeclasses-gradle-plugin")
    dokkaPublications.html {
        suppressInheritedMembers.set(true)
        failOnWarning.set(true)
    }
    dokkaSourceSets.main {
        val dokkaModuleFile = file("docs/dokka-module.md")
        if (dokkaModuleFile.exists()) {
            includes.from(dokkaModuleFile)
        }

        sourceLink {
            localDirectory.set(file("src/main/kotlin"))
            remoteUrl("https://github.com/wabbit-corp/kotlin-typeclasses/tree/master/gradle-plugin/src/main/kotlin")
            remoteLineSuffix.set("#L")
        }

    }
    pluginsConfiguration.html {
        // customStyleSheets.from("styles.css")
        // customAssets.from("logo.png")
        footerMessage.set("(c) Wabbit Consulting Corporation")
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
