// Generated by app-wabbit-dev setup. Do not edit by hand.
// managed-integrity-v1: GsF7rZQAwi9
//
// This file is generated from workspace configuration in root.clj.
// To change it, update root.clj and regenerate
// with the dev command, for example:
//   dev setup <project-or-repo>
// For durable imperative Gradle logic, use build.extra.gradle.kts beside this file.
// Direct edits to this file will be overwritten the next time setup runs.

import org.jetbrains.dokka.gradle.DokkaExtension
import org.jetbrains.dokka.gradle.engine.plugins.DokkaHtmlPluginParameters
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

fun String.parseWabbitBooleanFlag(flagName: String): Boolean =
    when (trim().lowercase()) {
        "true" -> true
        "false" -> false
        else -> error("$flagName must be true or false, got '$this'")
    }

val useMavenLocalArtifacts =
    providers.gradleProperty("wabbit.useMavenLocalArtifacts")
        .orElse(providers.environmentVariable("WABBIT_USE_MAVEN_LOCAL_ARTIFACTS"))
        .map { it.parseWabbitBooleanFlag("wabbit.useMavenLocalArtifacts") }
        .orElse(false)
        .get()

abstract class GenerateTypeclassGradlePluginVersion : DefaultTask() {
    @get:Input
    abstract val compilerPluginVersion: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            package one.wabbit.typeclass.gradle

            internal const val TYPECLASS_GRADLE_PLUGIN_VERSION: String = "${compilerPluginVersion.get()}"
            """.trimIndent(),
        )
    }
}

repositories {
    if (useMavenLocalArtifacts) {
        mavenLocal {
            content {
                includeGroup("one.wabbit")
                includeGroupByRegex("one\\.wabbit\\..+")
            }
        }
    }
    google()
    mavenCentral()

    maven("https://jitpack.io")
}

group   = "one.wabbit"

val configuredBaseVersionString = providers.gradleProperty("projectVersion").orElse("0.0.1").get()

val kotlinVersion =
    providers.gradleProperty("kotlinVersion")
        .orElse(providers.gradleProperty("defaultKotlinVersion"))
        .orElse("2.3.10")
        .get()

version = configuredBaseVersionString

plugins {
    kotlin("jvm")
    id("org.jetbrains.dokka")
    id("org.jetbrains.kotlinx.kover")

    `java-gradle-plugin`

    id("maven-publish")

    id("com.vanniktech.maven.publish")
}

mavenPublishing {
    coordinates("one.wabbit", "kotlin-typeclasses-gradle-plugin", project.version.toString())
    publishToMavenCentral()
    signAllPublications()
    pom {
        name.set("kotlin-typeclasses-gradle-plugin")
        description.set("Gradle plugin that wires the kotlin-typeclasses runtime and Kotlin-line-specific compiler plugin into Kotlin builds.")
        url.set("https://github.com/wabbit-corp/kotlin-typeclasses")
        licenses {
            license {
                name.set("GNU Affero General Public License v3.0 or later")
                url.set("https://spdx.org/licenses/AGPL-3.0-or-later.html")
            }
        }
        developers {
            developer {
                id.set("wabbit-corp")
                name.set("Wabbit Consulting Corporation")

                email.set("wabbit@wabbit.one")

            }
        }
        scm {
            url.set("https://github.com/wabbit-corp/kotlin-typeclasses")
            connection.set("scm:git:git://github.com/wabbit-corp/kotlin-typeclasses.git")
            developerConnection.set("scm:git:ssh://git@github.com/wabbit-corp/kotlin-typeclasses.git")
        }
    }
}

publishing {
    publications.withType<org.gradle.api.publish.maven.MavenPublication>().configureEach {
        if (name == "pluginMaven") {
            artifactId = "kotlin-typeclasses-gradle-plugin"
        }
    }
}

val localPublishRequested =
    gradle.startParameter.taskNames.any { taskName -> "MavenLocal" in taskName }

if (localPublishRequested) {
    tasks.withType<org.gradle.plugins.signing.Sign>().configureEach {
        enabled = false
    }
}

dependencies {
    implementation("one.wabbit:kotlin-gradle-plugin-common:0.0.1")

    compileOnly("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    testImplementation("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    testImplementation(gradleApi())
    testImplementation(gradleTestKit())

    testImplementation(kotlin("test"))
}

val generatedVersionSourceDirectory = layout.buildDirectory.dir("generated/sources/compilerPluginVersion/main/kotlin")

val generateCompilerGradlePluginVersion by tasks.registering(GenerateTypeclassGradlePluginVersion::class) {
    compilerPluginVersion.set(configuredBaseVersionString)
    outputFile.set(generatedVersionSourceDirectory.map { directory ->
        directory.file("one/wabbit/typeclass/gradle/TypeclassGradlePluginVersion.kt")
    })
}

kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(generatedVersionSourceDirectory)
    }
}

java {
    targetCompatibility = JavaVersion.toVersion(21)
    sourceCompatibility = JavaVersion.toVersion(21)
}

val configuredVersionString = version.toString()

val configuredBaseVersionForChecks = configuredBaseVersionString

tasks.register("printVersion") {
    inputs.property("configuredVersion", configuredVersionString)
    doLast {
        println(inputs.properties["configuredVersion"])
    }
}

tasks.register("printBaseVersion") {
    inputs.property("configuredBaseVersion", configuredBaseVersionForChecks)
    doLast {
        println(inputs.properties["configuredBaseVersion"])
    }
}

tasks.register("assertReleaseVersion") {
    inputs.property("configuredVersion", configuredBaseVersionForChecks)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(!versionString.endsWith("+dev-SNAPSHOT")) {
            "Release publishing requires a non-snapshot version, got $versionString"
        }
        val refType = System.getenv("GITHUB_REF_TYPE") ?: ""
        val refName = System.getenv("GITHUB_REF_NAME") ?: ""
        if (refType == "tag" && refName.isNotBlank()) {
            val expectedTag = "v$versionString"
            require(refName == expectedTag) {
                "Git tag $refName does not match project version $versionString"
            }
        }
    }
}

tasks.register("assertSnapshotVersion") {
    inputs.property("configuredVersion", configuredBaseVersionForChecks)
    doLast {
        val versionString = inputs.properties["configuredVersion"].toString()
        require(versionString.endsWith("+dev-SNAPSHOT")) {
            "Snapshot publishing requires a +dev-SNAPSHOT version, got $versionString"
        }
        require((System.getenv("GITHUB_REF_TYPE") ?: "") != "tag") {
            "Snapshot publishing must not run from a tag ref"
        }
    }
}

tasks {
    withType<Test> {
        jvmArgs("-ea")

    }
    withType<JavaCompile> {
        options.encoding = Charsets.UTF_8.name()
        options.release.set(21)
    }
    withType<Javadoc> {
        options.encoding = Charsets.UTF_8.name()
    }

    withType<KotlinCompile> {
        dependsOn(generateCompilerGradlePluginVersion)

        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
            freeCompilerArgs.add("-Xcontext-parameters")

        }
    }

    matching { it.name == "sourcesJar" }.configureEach {
        dependsOn(generateCompilerGradlePluginVersion)
    }
    matching { it.name.startsWith("dokka") }.configureEach {
        dependsOn(generateCompilerGradlePluginVersion)
    }

    jar {
        setProperty("zip64", true)

    }
}

gradlePlugin {
    plugins {
        create("typeclass") {
            id = "one.wabbit.typeclass"
            implementationClass = "one.wabbit.typeclass.gradle.TypeclassGradlePlugin"
            displayName = "Typeclass Gradle plugin"
            description = "Gradle plugin that wires the kotlin-typeclasses runtime and Kotlin-line-specific compiler plugin into Kotlin builds."
        }
    }
}

// Kover Configuration
kover {
    // useJacoco() // This is the default, can be specified if you want to be explicit
    // reports {
    //     // Configure reports for the default test task.
    //     // Kover tries to infer the variant for simple JVM projects.
    //     // If you have specific build types/flavors, you'd configure them here as variants.
    //     variant() { // Or remove "debug" for a default JVM setup unless you have variants
    //         html {
    //             // reportDir.set(layout.buildDirectory.dir("reports/kover/html")) // Uncomment to customize output
    //             // title.set("kotlin-typeclasses-gradle-plugin Code Coverage") // Uncomment to customize title
    //         }
    //         xml {
    //             // reportFile.set(layout.buildDirectory.file("reports/kover/coverage.xml")) // Uncomment to customize output
    //         }
    //     }
    // }
}

plugins.withId("org.jetbrains.dokka") {
    afterEvaluate {
        extensions.findByType(DokkaExtension::class)?.apply {
            moduleName.set("kotlin-typeclasses-gradle-plugin")
            dokkaPublications.named("html").configure {
                suppressInheritedMembers.set(true)
                failOnWarning.set(true)
            }
            dokkaSourceSets.named("main").configure {
                val dokkaModuleFile = file("docs/dokka-module.md")
                if (dokkaModuleFile.exists()) {
                    includes.from(dokkaModuleFile)
                }

                sourceLink {
                    localDirectory.set(file("src/main/kotlin"))
                    remoteUrl("https://github.com/wabbit-corp/kotlin-typeclasses/tree/master/gradle-plugin/src/main/kotlin")
                    remoteLineSuffix.set("#L")
                }

            }
            pluginsConfiguration.named(DokkaHtmlPluginParameters.DOKKA_HTML_PARAMETERS_NAME).configure {
                (this as DokkaHtmlPluginParameters).footerMessage.set("(c) Wabbit Consulting Corporation")
            }
        }
    }
}

val extraBuildFile = file("build.extra.gradle.kts")
if (extraBuildFile.isFile) {
    apply(from = extraBuildFile)
}
