// SPDX-License-Identifier: LicenseRef-Wabbit-Public-Test-License

package one.wabbit.typeclass.plugin.integration.derivation

import one.wabbit.typeclass.plugin.integration.CompilerHarnessPlugin
import one.wabbit.typeclass.plugin.integration.HarnessDependency
import one.wabbit.typeclass.plugin.integration.IntegrationTestSupport
import kotlin.test.Ignore
import kotlin.test.Test

/**
 * Specification for a future derivation-optimization pass.
 *
 * Goal:
 * - Keep the current derivation contract and observable semantics.
 * - Replace metadata-interpreter hot paths with code that is as close as possible to what a
 *   careful human would have handwritten for the same ADT.
 * - Treat `@Derive(JsonCodec::class)` as an opportunity to emit direct encode/decode logic for
 *   the concrete derived target, not merely a generic metadata-driven interpreter object.
 * - Treat `@DeriveVia(JsonCodec::class, Foo::class)` as an opportunity to keep only the minimal
 *   direct transport composition on the hot path.
 *
 * Current architecture:
 * - Derivation today is intentionally generic. The plugin emits metadata plus prerequisite
 *   instance slots, and the typeclass companion's `deriveProduct` / `deriveSum` / `deriveEnum`
 *   methods construct the runtime instance from that metadata.
 * - That design is flexible and semantically correct, but it leaves an optimization gap:
 *   many hot-path operations still iterate metadata, read field descriptors indirectly, scan
 *   sum cases linearly, or bounce through transport adapters whose structure is statically
 *   known at the derivation site.
 *
 * Desired end state:
 * - For local product derivation, the generated codec should look morally like:
 *
 *   `object : JsonCodec<Person> {`
 *   `  override fun encode(value: Person): JsonElement = buildJsonObject { ... direct field calls ... }`
 *   `  override fun decode(json: JsonElement): Person = Person(name = ..., age = ...)`
 *   `}`
 *
 * - For local sealed sums, the generated codec should look morally like:
 *
 *   `override fun encode(value: Expr): JsonElement = when (value) {`
 *   `  is Lit -> ...`
 *   `  is Add -> ...`
 *   `  End -> ...`
 *   `}`
 *
 *   and `decode` should dispatch directly on the discriminator rather than scanning candidate
 *   metadata records.
 *
 * - For `@DeriveVia(JsonCodec::class, Foo::class)` or pinned-Iso paths, the generated codec
 *   should look morally like:
 *
 *   `override fun encode(value: UserId): JsonElement = fooCodec.encode(userIdToFoo(value))`
 *   `override fun decode(json: JsonElement): UserId = fooToUserId(fooCodec.decode(json))`
 *
 *   with the transport chain composed once in generated code.
 *
 * Current `DeriveVia` status:
 * - The current backend already resolves the transport path at compile time and emits a bespoke
 *   adapter object; it is not doing runtime path search on every call.
 * - The remaining `DeriveVia` optimization target is therefore narrower than the plain `@Derive`
 *   target:
 *   remove unnecessary adapter allocation where possible, collapse identity transports, fuse
 *   local transport chains, and eliminate dead unwrap/rewrap pairs.
 *
 * Optimization scope:
 * - The pass should specialize plugin-generated derivation scaffolding.
 * - It may partially evaluate plugin-generated metadata access, field/case selection, direct
 *   constructor reconstruction, discriminator constants, enum-entry tables, and transport-plan
 *   composition.
 * - It should not attempt arbitrary global purity inference or arbitrary symbolic execution of
 *   user code.
 *
 * Safety / boundary rules:
 * - No cross-module inlining of user-authored codec logic.
 * - No cross-compilation-unit inlining of user-authored codec logic, even within the same module.
 *   A compilation unit here means a Kotlin source file.
 * - The pass may still reference stable external symbols directly:
 *   companion instances, top-level singleton instances, enum entries, constructors, getters,
 *   and pure plugin-generated transport helpers.
 * - If code lives in another compilation unit or module, generated code should call or load it,
 *   not clone its body.
 * - This avoids invalidating unrelated files too aggressively, keeps dynamic-link behavior sane,
 *   and avoids baking dependency internals into generated bytecode.
 *
 * Allowed local specialization:
 * - Within the same compilation unit, the pass may inline or partially evaluate a conservative
 *   whitelist of shapes when their full bodies are available and obviously stable:
 *   `const` values, enum entries, direct constructor calls, transparent value-class unwrap/rewrap,
 *   direct property getters on local data/value classes, pure plugin-generated lambdas, and tiny
 *   helper functions that are syntactically first-order and side-effect-free.
 * - This is intentionally narrower than "arbitrary pure Kotlin".
 * - If the proof obligation is not trivial, keep a direct call boundary instead of guessing.
 *
 * Observable success criteria:
 * - Product encode/decode hot paths have no iteration over `metadata.fields`.
 * - Sum encode/decode hot paths have no linear scan over `metadata.cases`.
 * - Enum encode/decode hot paths use direct entry-name tables or direct `when` dispatch.
 * - `DeriveVia` encode/decode hot paths invoke each transport boundary at most once per entry/exit.
 * - Recursive derivations allocate indirection cells only where the graph is actually recursive.
 * - Cross-file and cross-module helpers remain as symbol references rather than cloned bodies.
 *
 * Non-goals:
 * - Whole-program optimization.
 * - General partial evaluation of arbitrary user-authored Kotlin.
 * - Rewriting foreign-module helper bodies into the current module.
 * - Depending on backend JITs to recover obvious structure we can emit directly ourselves.
 *
 * Proposed implementation pipeline:
 * 1. Lower ordinary derivation first, producing an explicit derivation plan.
 * 2. Recognize optimizeable `JsonCodec`-shaped plans and `DeriveVia(JsonCodec, ...)` plans.
 * 3. Normalize transport plans and metadata access into a small internal SSA-like shape.
 * 4. Perform local, boundary-aware partial evaluation on that internal shape.
 * 5. Emit direct IR for products, sums, enums, and via-compositions.
 * 6. Run a tiny peephole pass to collapse identities, dead temporaries, redundant casts, and
 *    direct unwrap/rewrap pairs.
 *
 * Evidence / invalidation model:
 * - Local generated code may depend structurally on the current file's ADT shape.
 * - It may depend nominally on external helpers and external prerequisite instances through
 *   stable calls and loads only.
 * - Changes to an external helper implementation should not require the current file to be
 *   recompiled merely because the optimizer had previously cloned that implementation. The pass
 *   should therefore avoid such cloning.
 *
 * Test philosophy in this suite:
 * - These tests are specification fixtures first.
 * - Many are semantic scaffolds plus shape contracts in comments.
 * - Passing semantic output alone is not enough to prove optimization.
 * - For local interpreter-elimination cases, the fixtures therefore also define explicit counters
 *   for metadata-loop and case-scan hot paths; once the optimization pass exists those counters
 *   should drop to zero in the optimized fixtures.
 * - Those counters still do not prove every shape claim: constant field-name literals, direct
 *   discriminator literals, fused allocation shape, and direct symbol references across file
 *   boundaries will still need future IR/bytecode assertions.
 * - For cross-compilation-unit and cross-module boundary cases, semantic output alone still does
 *   not prove that a call boundary was preserved, so future work should extend the harness with
 *   IR/bytecode assertions and, for cross-module cases, dependency-swap validation.
 * - The recursive and `DeriveVia` fixtures are especially important examples of this limitation:
 *   the current counters do not observe recursive cell placement, allocation shape, or wrapper
 *   fusion by themselves.
 * - The comments under each test state the intended generated shape and the boundary rules that
 *   should hold once the optimization pass exists.
 *
 * JSON ordering policy in this suite:
 * - Field and discriminator ordering is intentionally part of the current spec.
 * - The target is "close to a straightforward handwritten codec", and a straightforward handwritten
 *   codec would usually emit fields in declaration order with the discriminator first for sums.
 */
@Ignore("Spec-only: derivation optimization pass is not implemented yet")
class DerivationOptimizationSpec : IntegrationTestSupport() {
    private val serializationRuntime = listOf(CompilerHarnessPlugin.SerializationRuntime)

    private val jsonCodecPrelude =
        """
        package demo

        import kotlinx.serialization.json.Json
        import kotlinx.serialization.json.JsonElement
        import kotlinx.serialization.json.JsonObject
        import kotlinx.serialization.json.JsonPrimitive
        import kotlinx.serialization.json.boolean
        import kotlinx.serialization.json.buildJsonObject
        import kotlinx.serialization.json.int
        import kotlinx.serialization.json.jsonObject
        import kotlinx.serialization.json.jsonPrimitive
        import one.wabbit.typeclass.Derive
        import one.wabbit.typeclass.DeriveVia
        import one.wabbit.typeclass.EnumTypeclassMetadata
        import one.wabbit.typeclass.Instance
        import one.wabbit.typeclass.Iso
        import one.wabbit.typeclass.ProductTypeclassMetadata
        import one.wabbit.typeclass.SumTypeclassMetadata
        import one.wabbit.typeclass.Typeclass
        import one.wabbit.typeclass.TypeclassDeriver
        import one.wabbit.typeclass.get
        import one.wabbit.typeclass.matches
        import one.wabbit.typeclass.summon

        enum class JsonCodecRepresentation {
            INLINE,
            OBJECT,
        }

        object OptimizationCounters {
            var productEncodeMetadataLoops: Int = 0
            var productDecodeMetadataLoops: Int = 0
            var sumEncodeCaseScans: Int = 0
            var sumDecodeCaseScans: Int = 0
            var enumDecodeLinearScans: Int = 0
        }

        fun resetOptimizationCounters() {
            OptimizationCounters.productEncodeMetadataLoops = 0
            OptimizationCounters.productDecodeMetadataLoops = 0
            OptimizationCounters.sumEncodeCaseScans = 0
            OptimizationCounters.sumDecodeCaseScans = 0
            OptimizationCounters.enumDecodeLinearScans = 0
        }

        fun snapshotOptimizationCounters(): String =
            listOf(
                OptimizationCounters.productEncodeMetadataLoops,
                OptimizationCounters.productDecodeMetadataLoops,
                OptimizationCounters.sumEncodeCaseScans,
                OptimizationCounters.sumDecodeCaseScans,
                OptimizationCounters.enumDecodeLinearScans,
            ).joinToString(separator = "|")

        @Typeclass
        interface JsonCodec<A> {
            val representation: JsonCodecRepresentation

            fun encode(value: A): JsonElement

            fun decode(json: JsonElement): A

            companion object : TypeclassDeriver {
                override fun deriveProduct(metadata: ProductTypeclassMetadata): Any =
                    object : JsonCodec<Any?> {
                        override val representation: JsonCodecRepresentation =
                            if (metadata.isValueClass) {
                                JsonCodecRepresentation.INLINE
                            } else {
                                JsonCodecRepresentation.OBJECT
                            }

                        override fun encode(value: Any?): JsonElement {
                            require(value != null)
                            if (metadata.isValueClass) {
                                val field = metadata.fields.single()
                                val fieldCodec = field.instance as JsonCodec<Any?>
                                return fieldCodec.encode(field.get(value))
                            }
                            OptimizationCounters.productEncodeMetadataLoops += 1
                            return buildJsonObject {
                                metadata.fields.forEach { field ->
                                    val fieldCodec = field.instance as JsonCodec<Any?>
                                    put(field.name, fieldCodec.encode(field.get(value)))
                                }
                            }
                        }

                        override fun decode(json: JsonElement): Any? {
                            if (metadata.isValueClass) {
                                val field = metadata.fields.single()
                                val fieldCodec = field.instance as JsonCodec<Any?>
                                return metadata.construct(fieldCodec.decode(json))
                            }
                            val jsonObject = json.jsonObject
                            OptimizationCounters.productDecodeMetadataLoops += 1
                            val fieldValues =
                                metadata.fields.map { field ->
                                    val fieldCodec = field.instance as JsonCodec<Any?>
                                    fieldCodec.decode(jsonObject.getValue(field.name))
                                }
                            return metadata.construct(*fieldValues.toTypedArray())
                        }
                    }

                override fun deriveSum(metadata: SumTypeclassMetadata): Any =
                    object : JsonCodec<Any?> {
                        override val representation: JsonCodecRepresentation = JsonCodecRepresentation.OBJECT

                        override fun encode(value: Any?): JsonElement {
                            require(value != null)
                            OptimizationCounters.sumEncodeCaseScans += 1
                            val selected = metadata.cases.single { candidate -> candidate.matches(value) }
                            val caseCodec = selected.instance as JsonCodec<Any?>
                            val payload = caseCodec.encode(value)
                            return when (caseCodec.representation) {
                                JsonCodecRepresentation.INLINE ->
                                    buildJsonObject {
                                        put("type", JsonPrimitive(selected.name))
                                        put("value", payload)
                                    }

                                JsonCodecRepresentation.OBJECT ->
                                    buildJsonObject {
                                        put("type", JsonPrimitive(selected.name))
                                        payload.jsonObject.forEach { (key, fieldValue) -> put(key, fieldValue) }
                                    }
                            }
                        }

                        override fun decode(json: JsonElement): Any? {
                            val jsonObject = json.jsonObject
                            val tag = jsonObject.getValue("type").jsonPrimitive.content
                            OptimizationCounters.sumDecodeCaseScans += 1
                            val selected = metadata.cases.single { candidate -> candidate.name == tag }
                            val caseCodec = selected.instance as JsonCodec<Any?>
                            val payload =
                                when (caseCodec.representation) {
                                    JsonCodecRepresentation.INLINE -> jsonObject.getValue("value")
                                    JsonCodecRepresentation.OBJECT ->
                                        JsonObject(jsonObject.filterKeys { key -> key != "type" })
                                }
                            return caseCodec.decode(payload)
                        }
                    }

                override fun deriveEnum(metadata: EnumTypeclassMetadata): Any =
                    object : JsonCodec<Any?> {
                        override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

                        override fun encode(value: Any?): JsonElement {
                            require(value != null)
                            return JsonPrimitive(metadata.entries[metadata.ordinalOf(value)].name)
                        }

                        override fun decode(json: JsonElement): Any? {
                            val name = json.jsonPrimitive.content
                            OptimizationCounters.enumDecodeLinearScans += 1
                            val index = metadata.entries.indexOfFirst { entry -> entry.name == name }
                            require(index >= 0) { "Unknown enum entry: ${'$'}name" }
                            return metadata.valueAt(index)
                        }
                    }
            }
        }

        @Instance
        object IntJsonCodec : JsonCodec<Int> {
            override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

            override fun encode(value: Int): JsonElement = JsonPrimitive(value)

            override fun decode(json: JsonElement): Int = json.jsonPrimitive.int
        }

        @Instance
        object StringJsonCodec : JsonCodec<String> {
            override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

            override fun encode(value: String): JsonElement = JsonPrimitive(value)

            override fun decode(json: JsonElement): String = json.jsonPrimitive.content
        }

        @Instance
        object BooleanJsonCodec : JsonCodec<Boolean> {
            override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

            override fun encode(value: Boolean): JsonElement = JsonPrimitive(value)

            override fun decode(json: JsonElement): Boolean = json.jsonPrimitive.boolean
        }

        fun compact(json: JsonElement): String = Json { prettyPrint = false }.encodeToString(JsonElement.serializer(), json)

        context(codec: JsonCodec<A>)
        fun <A> roundTrip(value: A): A = codec.decode(codec.encode(value))

        context(codec: JsonCodec<A>)
        fun <A> encodeToString(value: A): String = compact(codec.encode(value))
        """.trimIndent()

    @Test
    fun optimizesLocalProductJsonCodecsToStraightLineFieldCode() {
        val source =
            """
            $jsonCodecPrelude

            @Derive(JsonCodec::class)
            data class Person(val name: String, val age: Int, val admin: Boolean)

            fun main() {
                resetOptimizationCounters()
                println(encodeToString(Person("Ada", 3, true)))
                println(roundTrip(Person("Ada", 3, true)))
                println(snapshotOptimizationCounters())
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - The optimized codec for Person should not iterate `metadata.fields` on each encode/decode call.
        // - Encode should become straight-line code that reads `value.name`, `value.age`, and `value.admin`
        //   directly and calls the three prerequisite codecs directly.
        // - Decode should become a direct `Person(...)` constructor call, not `metadata.construct(...)`,
        //   whenever the primary constructor is directly available and stable.
        // - The hot path should not read field names from metadata at runtime; JSON key strings should be
        //   constant literals in the generated code.
        // - This is the canonical "be as close to handwritten as possible" product case.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                {"name":"Ada","age":3,"admin":true}
                Person(name=Ada, age=3, admin=true)
                0|0|0|0|0
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun optimizesDirectValueClassJsonCodecsToInlineUnwrapRewrap() {
        val source =
            """
            $jsonCodecPrelude

            @JvmInline
            @Derive(JsonCodec::class)
            value class UserId(val value: Int)

            fun main() {
                resetOptimizationCounters()
                println(encodeToString(UserId(7)))
                println(roundTrip(UserId(9)))
                println(snapshotOptimizationCounters())
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - A directly derived value-class codec should be the simplest inline bridge possible.
        // - Encode should reduce to the field codec over `value.value`.
        // - Decode should reduce to `UserId(fieldCodec.decode(json))`.
        // - No product metadata loop should remain, and no heap object should be required on the hot path.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                7
                UserId(value=9)
                0|0|0|0|0
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun optimizesLocalSealedJsonCodecsToDirectCaseDispatch() {
        val source =
            """
            $jsonCodecPrelude

            @Derive(JsonCodec::class)
            sealed interface Expr

            @Derive(JsonCodec::class)
            @JvmInline
            value class InlineLit(val value: Int) : Expr

            @Derive(JsonCodec::class)
            data class Add(val left: Expr, val right: Expr) : Expr

            @Derive(JsonCodec::class)
            data object End : Expr

            fun main() {
                resetOptimizationCounters()
                val inline: Expr = InlineLit(1)
                println(encodeToString(inline))
                println(roundTrip(inline))
                println(snapshotOptimizationCounters())
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - Encode should become a direct `when (value)` over the sealed cases.
        // - Decode should dispatch directly on the discriminator string rather than scanning
        //   `metadata.cases.single { ... }`.
        // - This fixture intentionally exercises the INLINE sum branch via `InlineLit`.
        // - Case tags should be constant literals.
        // - Case-codec prerequisite references should be direct stable loads/calls.
        // - No per-call `matches(...)` loop should remain in the optimized hot path.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                {"type":"InlineLit","value":1}
                InlineLit(value=1)
                0|0|0|0|0
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun optimizesEnumJsonCodecsToDirectEntryTables() {
        val source =
            """
            $jsonCodecPrelude

            @Derive(JsonCodec::class)
            enum class Priority {
                LOW,
                HIGH,
            }

            fun main() {
                resetOptimizationCounters()
                println(encodeToString(Priority.HIGH))
                println(roundTrip(Priority.LOW))
                println(snapshotOptimizationCounters())
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - Encode should be equivalent to a direct name-table lookup or direct `when` on the enum entry.
        // - Decode should be equivalent to a direct string-switch or direct table lookup.
        // - No generic `metadata.entries.indexOfFirst` loop should remain on the hot path once optimized.
        // - This is the enum analogue of handwritten serializer code.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                "HIGH"
                LOW
                0|0|0|0|0
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun keepsRecursiveIndirectionOnlyAtTrueRecursiveKnots() {
        val source =
            """
            $jsonCodecPrelude

            @Derive(JsonCodec::class)
            sealed interface Tree

            @Derive(JsonCodec::class)
            data class Leaf(val value: Int) : Tree

            @Derive(JsonCodec::class)
            data class Branch(val left: Tree, val right: Tree) : Tree

            fun main() {
                resetOptimizationCounters()
                val value: Tree = Branch(Leaf(1), Branch(Leaf(2), Leaf(3)))
                println(encodeToString(value))
                println(roundTrip(value))
                println(snapshotOptimizationCounters())
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - Recursion cells or recursive resolver slots are allowed only on the recursive edges that
        //   actually need them.
        // - Non-recursive field codecs such as `IntJsonCodec` should remain direct calls.
        // - The optimizer should not pessimize the entire codec into an indirect interpreter just
        //   because one branch is recursive.
        // - The current fixture only makes the ordinary metadata-loop counters observable.
        // - True proof about recursive cells still requires future IR/bytecode assertions or dedicated
        //   recursive-cell instrumentation.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                {"type":"Branch","left":{"type":"Leaf","value":1},"right":{"type":"Branch","left":{"type":"Leaf","value":2},"right":{"type":"Leaf","value":3}}}
                Branch(left=Leaf(value=1), right=Branch(left=Leaf(value=2), right=Leaf(value=3)))
                0|0|0|0|0
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun observesDeriveViaSingleStepBoundaryCallCounts() {
        val source =
            """
            $jsonCodecPrelude

            object Counters {
                var toFoo: Int = 0
                var fromFoo: Int = 0
                var encodeFoo: Int = 0
                var decodeFoo: Int = 0
            }

            data class Foo(val value: Int)

            object UserIdFooIso : Iso<UserId, Foo> {
                override fun to(value: UserId): Foo {
                    Counters.toFoo += 1
                    return Foo(value.value)
                }

                override fun from(value: Foo): UserId {
                    Counters.fromFoo += 1
                    return UserId(value.value)
                }
            }

            @Instance
            object FooJsonCodec : JsonCodec<Foo> {
                override val representation: JsonCodecRepresentation = JsonCodecRepresentation.OBJECT

                override fun encode(value: Foo): JsonElement {
                    Counters.encodeFoo += 1
                    return buildJsonObject {
                        put("value", JsonPrimitive(value.value))
                    }
                }

                override fun decode(json: JsonElement): Foo {
                    Counters.decodeFoo += 1
                    return Foo(json.jsonObject.getValue("value").jsonPrimitive.int)
                }
            }

            @JvmInline
            @DeriveVia(JsonCodec::class, UserIdFooIso::class)
            value class UserId(val value: Int)

            fun main() {
                val codec = summon<JsonCodec<UserId>>()
                println(compact(codec.encode(UserId(7))))
                println(codec.decode(buildJsonObject { put("value", JsonPrimitive(9)) }))
                println("${'$'}{Counters.toFoo}|${'$'}{Counters.fromFoo}|${'$'}{Counters.encodeFoo}|${'$'}{Counters.decodeFoo}")
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - Current DeriveVia lowering already resolves the path at compile time and emits a bespoke adapter.
        // - The optimization target here is therefore narrower than "eliminate runtime path search":
        //   keep the hot path to one encode-side transport, one via-codec call, one decode-side via-codec call,
        //   and one decode-side transport, with no redundant identity or unwrap/rewrap steps left over.
        // - Encode should be exactly `FooJsonCodec.encode(UserIdFooIso.to(value))`.
        // - Decode should be exactly `UserIdFooIso.from(FooJsonCodec.decode(json))`.
        // - Each transport boundary should be invoked once per direction on the hot path.
        // - This fixture observes single-call boundaries only; future IR/bytecode or allocation assertions
        //   are still needed to prove there is no nested dead adapter scaffolding left behind.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                {"value":7}
                UserId(value=9)
                1|1|1|1
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun normalizesStructuralDeriveViaWaypointsToDirectViaCodecCalls() {
        val source =
            """
            $jsonCodecPrelude

            object Counters {
                var encodeFoo: Int = 0
                var decodeFoo: Int = 0
            }

            data class Foo(val value: Int)

            @Instance
            object FooJsonCodec : JsonCodec<Foo> {
                override val representation: JsonCodecRepresentation = JsonCodecRepresentation.OBJECT

                override fun encode(value: Foo): JsonElement {
                    Counters.encodeFoo += 1
                    return buildJsonObject {
                        put("value", JsonPrimitive(value.value))
                    }
                }

                override fun decode(json: JsonElement): Foo {
                    Counters.decodeFoo += 1
                    return Foo(json.jsonObject.getValue("value").jsonPrimitive.int)
                }
            }

            @JvmInline
            @DeriveVia(JsonCodec::class, Foo::class)
            value class UserId(val value: Int)

            fun main() {
                val codec = summon<JsonCodec<UserId>>()
                println(compact(codec.encode(UserId(4))))
                println(codec.decode(buildJsonObject { put("value", JsonPrimitive(5)) }))
                println("${'$'}{Counters.encodeFoo}|${'$'}{Counters.decodeFoo}")
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - This is the plain structural-waypoint DeriveVia case, not pinned-Iso plumbing.
        // - The optimizer should normalize the structural Equiv<UserId, Foo> once and keep the hot path
        //   to one via-codec encode and one via-codec decode, with direct structural unwrap/rewrap around them.
        // - Like the pinned-Iso fixture above, this still only observes call counts; future shape assertions
        //   must prove the absence of dead wrapper scaffolding.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                {"value":4}
                UserId(value=5)
                1|1
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun observesLocalMultiStepDeriveViaBoundaryCallCounts() {
        val source =
            """
            $jsonCodecPrelude

            object Counters {
                var toMid: Int = 0
                var fromMid: Int = 0
                var toFoo: Int = 0
                var fromFoo: Int = 0
            }

            class Mid(val code: String) {
                override fun equals(other: Any?): Boolean = other is Mid && other.code == code
                override fun hashCode(): Int = code.hashCode()
                override fun toString(): String = "Mid(code=${'$'}code)"
            }

            class Foo(val payload: String) {
                override fun equals(other: Any?): Boolean = other is Foo && other.payload == payload
                override fun hashCode(): Int = payload.hashCode()
                override fun toString(): String = "Foo(payload=${'$'}payload)"
            }

            object UserIdMidIso : Iso<UserId, Mid> {
                override fun to(value: UserId): Mid {
                    Counters.toMid += 1
                    return Mid("mid:${'$'}{value.value}")
                }

                override fun from(value: Mid): UserId {
                    Counters.fromMid += 1
                    return UserId(value.code.removePrefix("mid:").toInt())
                }
            }

            object MidFooIso : Iso<Mid, Foo> {
                override fun to(value: Mid): Foo {
                    Counters.toFoo += 1
                    return Foo("foo:${'$'}{value.code}")
                }

                override fun from(value: Foo): Mid {
                    Counters.fromFoo += 1
                    return Mid(value.payload.removePrefix("foo:"))
                }
            }

            @Instance
            object FooJsonCodec : JsonCodec<Foo> {
                override val representation: JsonCodecRepresentation = JsonCodecRepresentation.OBJECT

                override fun encode(value: Foo): JsonElement =
                    buildJsonObject {
                        put("payload", JsonPrimitive(value.payload))
                    }

                override fun decode(json: JsonElement): Foo =
                    Foo(json.jsonObject.getValue("payload").jsonPrimitive.content)
            }

            @JvmInline
            @DeriveVia(JsonCodec::class, UserIdMidIso::class, MidFooIso::class)
            value class UserId(val value: Int)

            fun main() {
                val codec = summon<JsonCodec<UserId>>()
                println(compact(codec.encode(UserId(4))))
                println(codec.decode(buildJsonObject { put("payload", JsonPrimitive("foo:mid:5")) }))
                println("${'$'}{Counters.toMid}|${'$'}{Counters.fromMid}|${'$'}{Counters.toFoo}|${'$'}{Counters.fromFoo}")
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - The optimizer should compose the local transport chain once and emit a direct composite
        //   path rather than nesting generic transport adapters.
        // - `Mid` and `Foo` are intentionally plain nominal classes here so the pinned second segment is
        //   not already structurally transportable by the ordinary Equiv solver.
        // - Encode should morally be `FooJsonCodec.encode(MidFooIso.to(UserIdMidIso.to(value)))`.
        // - Decode should morally be `UserIdMidIso.from(MidFooIso.from(FooJsonCodec.decode(json)))`.
        // - The remaining optimization target is transport fusion and dead-step elimination, not runtime path search.
        // - This fixture observes call counts, not allocation shape. Future shape assertions are still needed to
        //   prove that the chain is represented as one fused plan rather than nested forwarding shells.
        assertCompilesAndRuns(
            source = source,
            expectedStdout =
                """
                {"payload":"foo:mid:4"}
                UserId(value=5)
                1|1|1|1
                """.trimIndent(),
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun mayInlineSameFileTinyPureHelpers() {
        val source =
            """
            $jsonCodecPrelude

            private fun encodeStringSameFile(value: String): JsonElement = JsonPrimitive("same-file:${'$'}value")

            @Instance
            object SameFileStringJsonCodec : JsonCodec<String> {
                override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

                override fun encode(value: String): JsonElement = encodeStringSameFile(value)

                override fun decode(json: JsonElement): String = json.jsonPrimitive.content.removePrefix("same-file:")
            }

            @Derive(JsonCodec::class)
            data class Labelled(val value: String)

            fun main() {
                println(encodeToString(Labelled("x")))
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - This fixture marks the positive side of the local-specialization boundary.
        // - If the optimizer can trivially prove that `encodeStringSameFile` is a tiny pure helper in the same
        //   compilation unit, it may inline or partially evaluate through it.
        // - This is an allowance, not an obligation; the important point is that same-file purity is where
        //   aggressive local specialization may begin.
        assertCompilesAndRuns(
            source = source,
            expectedStdout = """{"value":"same-file:x"}""",
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun keepsDirectBoundariesForNonTrivialSameFileHelpers() {
        val source =
            """
            $jsonCodecPrelude

            object LocalState {
                var prefix: String = "stateful"
            }

            private fun encodeStringStatefully(value: String): JsonElement =
                JsonPrimitive("${'$'}{LocalState.prefix}:${'$'}value")

            @Instance
            object StatefulStringJsonCodec : JsonCodec<String> {
                override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

                override fun encode(value: String): JsonElement = encodeStringStatefully(value)

                override fun decode(json: JsonElement): String = json.jsonPrimitive.content.removePrefix("${'$'}{LocalState.prefix}:")
            }

            @Derive(JsonCodec::class)
            data class Labelled(val value: String)

            fun main() {
                println(encodeToString(Labelled("x")))
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - Same-file visibility alone is not enough.
        // - The helper here reads mutable state, so the optimizer should keep a direct call boundary unless
        //   it has a proof stronger than the current spec is willing to require.
        // - This fixture is therefore the negative counterpart to the tiny-pure-helper allowance above.
        assertCompilesAndRuns(
            source = source,
            expectedStdout = """{"value":"stateful:x"}""",
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun doesNotInlineUserCodecBodiesAcrossCompilationUnits() {
        val sources =
            mapOf(
                "Prelude.kt" to jsonCodecPrelude,
                "Codecs.kt" to
                    """
                    package demo

                    import kotlinx.serialization.json.JsonElement
                    import kotlinx.serialization.json.JsonPrimitive
                    import one.wabbit.typeclass.Instance
                    import kotlinx.serialization.json.jsonPrimitive

                    data class LabelText(val raw: String)

                    fun encodeLabelTextPayload(value: String): JsonElement = JsonPrimitive("external:${'$'}value")

                    fun decodeLabelTextPayload(json: JsonElement): String = json.jsonPrimitive.content.removePrefix("external:")

                    @Instance
                    object LabelTextJsonCodec : JsonCodec<LabelText> {
                        override val representation: JsonCodecRepresentation = JsonCodecRepresentation.INLINE

                        override fun encode(value: LabelText): JsonElement = encodeLabelTextPayload(value.raw)

                        override fun decode(json: JsonElement): LabelText = LabelText(decodeLabelTextPayload(json))
                    }
                    """.trimIndent(),
                "Sample.kt" to
                    """
                    package demo

                    import one.wabbit.typeclass.Derive

                    @Derive(JsonCodec::class)
                    data class Labelled(val value: LabelText)

                    fun main() {
                        println(encodeToString(Labelled(LabelText("x"))))
                    }
                    """.trimIndent(),
            )

        // Exact intended optimization semantics:
        // - The optimizer may still specialize `Labelled` as a product codec.
        // - `LabelTextJsonCodec` is legal here because it is declared in the same file as `LabelText`.
        // - The forbidden transformation is cloning `LabelTextJsonCodec.encode` / `decode` into the generated
        //   `Labelled` codec merely because the prerequisite codec is visible in the same module.
        // - The helper function is secondary; future shape assertions should target symbol references to
        //   `LabelTextJsonCodec.encode` / `decode`, not just the helper call.
        // - This fixture is only a semantic scaffold today; future work should add IR/bytecode assertions
        //   proving that the generated product codec still calls the codec object rather than a cloned body.
        assertCompilesAndRuns(
            sources = sources,
            mainClass = "demo.SampleKt",
            expectedStdout = """{"value":"external:x"}""",
            requiredPlugins = serializationRuntime,
        )
    }

    @Test
    fun doesNotInlineUserCodecBodiesAcrossModules() {
        val dependency =
            HarnessDependency(
                name = "upstream",
                sources =
                    mapOf(
                        "Upstream.kt" to
                            """
                            package upstream

                            import kotlinx.serialization.json.JsonElement
                            import kotlinx.serialization.json.JsonPrimitive
                            import one.wabbit.typeclass.Instance
                            import one.wabbit.typeclass.Typeclass

                            @Typeclass
                            interface JsonCodec<A> {
                                fun encode(value: A): JsonElement
                                fun decode(json: JsonElement): A
                            }

                            data class Foo(val value: Int)

                            @Instance
                            object FooJsonCodec : JsonCodec<Foo> {
                                override fun encode(value: Foo): JsonElement = JsonPrimitive("dep:${'$'}{value.value}")

                                override fun decode(json: JsonElement): Foo = Foo(0)
                            }
                            """.trimIndent(),
                    ),
                requiredPlugins = serializationRuntime,
            )

        val source =
            """
            package demo

            import kotlinx.serialization.json.JsonElement
            import one.wabbit.typeclass.DeriveVia
            import one.wabbit.typeclass.Instance
            import one.wabbit.typeclass.Iso
            import one.wabbit.typeclass.summon
            import upstream.Foo
            import upstream.JsonCodec

            object UserIdFooIso : Iso<UserId, Foo> {
                override fun to(value: UserId): Foo = Foo(value.value)
                override fun from(value: Foo): UserId = UserId(value.value)
            }

            @JvmInline
            @DeriveVia(JsonCodec::class, UserIdFooIso::class)
            value class UserId(val value: Int)

            fun main() {
                val codec = summon<JsonCodec<UserId>>()
                println(codec.encode(UserId(6)))
                println(codec.decode(JsonPrimitive("dep:7")))
            }
            """.trimIndent()

        // Exact intended optimization semantics:
        // - Cross-module prerequisite codecs remain stable symbol references.
        // - The optimizer may still collapse the local transport composition around them.
        // - It must not inline or clone the dependency module's `FooJsonCodec.encode` body into the
        //   current compilation output, and the same applies to `FooJsonCodec.decode`.
        // - This fixture's one-shot stdout check is only a semantic scaffold.
        // - The real boundary proof should eventually be a dependency-swap harness:
        //   compile upstream v1 + consumer, run; recompile upstream only with changed helper behavior;
        //   rerun the unchanged consumer against the new upstream jar; behavior must change if the call
        //   boundary was preserved.
        assertCompilesAndRuns(
            sources = mapOf("Sample.kt" to source),
            expectedStdout =
                """
                "dep:6"
                UserId(value=0)
                """.trimIndent(),
            mainClass = "demo.SampleKt",
            dependencies = listOf(dependency),
            requiredPlugins = serializationRuntime,
        )
    }
}
